charge:
    metrics:
        pt:
            x_range: [20, 180]
            n_bins: 9
            x_maj_tick_spacing: 40
        eta:
            x_range: [-2.6, 2.6]
            n_bins: 9
            x_maj_tick_spacing: 1
        theta:
            x_range: [10, 90]
            n_bins: 9
            x_maj_tick_spacing: 20
    cuts:
        min_pt: 20
        min_theta: 10
        max_theta: 170