tagging:
    base_dir: /path/to/base/dir
    algorithms:
        ParticleTransformer:
            data_dir: ${tagging.base_dir}
    performances:
        efficiency:
            xlabel:
                pt: "$p_T^{gen\\mathrm{-}\\tau_h}\\,\\, [GeV]$"
                eta: "$\\eta^{gen\\mathrm{-}\\tau_h}\\,\\, [GeV]$"
                theta: "$\\theta^{gen\\mathrm{-}\\tau_h}\\,\\, [ ^{o} ]$"
            ylabel: "$\\varepsilon_{\\tau}$"
            yscale: "linear"
            ylim: [0, 1]
        fakerate:
            xlabel:
                pt: "$p_T^{gen\\mathrm{-}jet}\\,\\, [GeV]$"
                eta: "$\\eta^{gen\\mathrm{-}jet}\\,\\, [GeV]$"
                theta: "$\\theta^{gen\\mathrm{-}jet}\\,\\, [ ^{o} ]$"
            ylabel: "$P_{misid}$"
            yscale: "log"
            ylim: [5e-6, 1e0]
    cuts:
        min_pt: 20
        min_theta: 10
        max_theta: 170
    metrics:
        pt:
            x_range: [20, 180]
            n_bins: 9
            x_maj_tick_spacing: 40
        eta:
            x_range: [-2.6, 2.6]
            n_bins: 9
            x_maj_tick_spacing: 1
        theta:
            x_range: [10, 90]
            n_bins: 9
            x_maj_tick_spacing: 20
